config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  post '/hunts/:id/join' => "hunts#join", :as => 'hunt_join'
  post '/hunts/:id/unjoin' => "hunts#unjoin", :as => 'hunt_unjoin'
  post '/hunts/search', :as => 'hunt_search'
  patch '/users/:id/update_public' => "users#update_public", :as => 'users_profile'
  get '/welcome/team', :as => 'contact_us'
  get '/welcome/careers', :as => 'careers'
  get '/welcome/about', :as => 'about'

  root "welcome#index"


  resources :hunts do
    resources :tasks do
      resources :completed_tasks, only: [:new, :create]
    end
    resources :comments
  end

  resources :categories
  resources :users
  resources :sessions

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :participations, dependent: :destroy
  has_many :participated_hunts, through: :participations, source: :hunt
  has_many :completed_tasks, dependent: :destroy
  has_many :tasks, through: :completed_tasks
  has_many :hunts #owned_hunt
  has_many :comments, dependent: :destroy

  validates :first_name, :last_name, presence: true
  validates :password, confirmation: true, on: :create
  validates :password_confirmation, presence: true, on: :create
  validates :email, presence: true, on: :create
  validates :email, uniqueness: true

  def full_name
    return "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @completed_tasks = @user.completed_tasks
  end

  def new
    @user = User.new
    flash[:previous_page] = request.referer
  end

  def create
    @user = User.new
    @user.first_name = params[:user][:first_name]
    @user.last_name = params[:user][:last_name]
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]
    if @user.save
      session[:user_id] = @user.id
      redirect_to request.referer, notice: "Logged in as #{@user.first_name} #{@user.last_name}!"
    else
      redirect_to request.referer, notice: "signup failed !"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update_public
    @user = User.find(params[:id])
    @user.public = params[:user][:public]
    if @user.save
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    @user.first_name = params[:user][:first_name]
    @user.last_name = params[:user][:last_name]
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]
    if @user.save
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_url
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_form.html.erb
<div class="sign_up_form animated fadeInDown">


  <div class="close_sign_up">
    <%= button_tag "x" %>
  </div>
  <%= form_for sign_up do |f| %>
    <div class="first_name_field">
      <h3><%= f.label :first_name %></h3>
      <%= f.text_field :first_name %>
    </div>
    <div class="last_name_field">
      <h3><%= f.label :last_name %></h3>
      <%= f.text_field :last_name %>
    </div>
    <div class="email_field">
      <h3><%= f.label :email %></h3>
      <%= f.text_field :email %>
    </div>
    <div class="password_field">
      <h3><%= f.label :password %></h3>
      <%= f.password_field :password %>
    </div>
    <div class="password_field">
      <h3><%= f.label :password_confirmation %></h3>
      <%= f.password_field :password_confirmation %>
    </div>
      <h3><%= f.submit "Sign up" %></h3>
  <% end %>
</div>

app/views/users/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/users/delete.html.erb
<h1>User#delete</h1>
<p>Find me in app/views/user/delete.html.erb</p>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>

<%= form_for @user do |f| %>



<div class="error_css">
<%  if @user.errors.any? %>
  <h2> Errors: </h2>
  <ul>
      <%  @user.errors.full_messages.each do |message| %>
        <li> <%= message %> </li>
      <% end  %>
  </ul>
<% end %>
</div>

  <div class="field">
    <h3><%= f.label :first_name %></h3>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <h3><%= f.label :last_name %></h3>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <h3><%= f.label :email %></h3>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <h3><%= f.label :password %></h3>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <h3><%= f.label :password_confirmation %></h3>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="field">
    <h3><%= f.submit %></h3>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>User#new</h1>



<div class="sign_up_form">

  <%= form_for @user do |f| %>

    <div class="error_css">
  <%  if @user.errors.any? %>
      <h2> Errors: </h2>
      <ul>
          <%  @user.errors.full_messages.each do |message| %>
            <li> <%= message %> </li>
          <% end  %>
      </ul>
  <% end %>


  </div>

    <div class="field">
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>

    <div class="field">
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>

    <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>

    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>

    <div class="field">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="user_info" id="user_info">
  <h1><%= @user.full_name %></h1>

  <% if @user.public == false && current_user != @user %>
      <p> this profile is private! </p>
  <% else %>
    <h2><%= @user.email %></h2>
    <h2>Completed Tasks: <%= @user.completed_tasks.length %></h2>

  <% if current_user == @user %>
      <%= form_for(@user, url: users_profile_path, html: {class: "security"}) do |f| %>
        <% if @user.public == true %>
          <%= f.hidden_field :public, :value => false %>
            <%= f.submit "Set to private", :class => 'set_public' %>
          </div>
        <% else %>
          <%= f.hidden_field :public, :value => true %>
            <%= f.submit "Set to public", :class => 'set_private' %>
        <% end %>
      <% end %>
      </div>
    <% end %>

    <div class="edit_profile">
      <% if current_user && current_user[:id] == @user.id %>
        <%= link_to 'Edit profile', edit_user_path%>
        <%= link_to 'Delete profile', user_path(@user) ,method: :delete, data: {confirm: "Are you sure you want to delete this profile This cannot be undone!"} %>
      <% end %>
    </div>
</div>

  <%if @user.hunts.future_hunts.length > 0 %>
  <h2>Future Hunts created:</h2>
    <% @user.hunts.future_hunts.each do |hunt| %>
        <div class="hunt">
          <li> <%=link_to("#{hunt.name}", hunt_path(hunt))%> </li>
          <p> Date: <%= hunt.hunt_date.strftime("%A %b %d %Y") %> | In <%= ((hunt.hunt_date - DateTime.now)/1.day).round(0) %> days time </p>
          <p> Participants: <%= hunt.participations.length %> </p>
          <p> Available spots: <%= hunt.available_spots %> </p>
        </div>
    <% end  %>
  <% end  %>

  <%if @user.hunts.past_hunts.length > 0%>
    <h2>Past Hunts created:</h2>
    <% @user.hunts.past_hunts.each do |hunt| %>
        <div class="hunt">
          <li> <%=link_to("#{hunt.name}", hunt_path(hunt))%> </li>
          <p> Date: <%= hunt.hunt_date.strftime("%A %b %d %Y") %> </p>
          <p> Participants: <%= hunt.participations.length %> </p>
        </div>
    <% end  %>
  <% end  %>
<div class="participations">
  <div class="participations_future">
    <%if @user.participated_hunts.future_hunts.length > 0%>
      <h2>Participations in future Hunts:</h2>
      <% @user.participated_hunts.future_hunts.each do |hunt| %>
        <div class="hunt_joined">
          <p> <%= link_to("#{hunt.name}", hunt_path(hunt))%> </p>
          <p>Date: <%= hunt.hunt_date.strftime("%A %b %d %Y")%> | In <%= ((hunt.hunt_date - DateTime.now)/1.day).round(0) %> days time </p>
        </div>
      <% end %>
    <% end %>
  </div>


  <div class="participations_past">
    <%if @user.participated_hunts.past_hunts.length > 0%>
      <h2>Participations in past Hunts:</h2>
      <% @user.participated_hunts.past_hunts.each do |hunt| %>
        <div class="hunt_joined">
          <p> <%= link_to("#{hunt.name}", hunt_path(hunt))  %> </p>
          <p> Date: <%= hunt.hunt_date.strftime("%A %b %d %Y") %></p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<div class="tasks_completed">
    <h2>Tasks completed:</h2>
    <% @completed_tasks.each do |task| %>
      <div class="completed_task">
        <p> <%= link_to "#{task.task.details}", "/hunts/#{task.task.hunt_id}/tasks/#{task.task.id}" %> </p>
        <% if task.proof  %>
          <p>Proof : <%= task.proof %></p>
        <% end  %>
        <div class="image_proof">
        <% if task.image.attached? %>
          <%= image_tag(task.image) %>
        <% end %>
        </div>
      </div>
    <% end %>
  </div>



<% end %>