config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  post '/hunts/:id/join' => "hunts#join", :as => 'hunt_join'
  post '/hunts/:id/unjoin' => "hunts#unjoin", :as => 'hunt_unjoin'
  post '/hunts/search', :as => 'hunt_search'
  patch '/users/:id/update_public' => "users#update_public", :as => 'users_profile'
  get '/welcome/team', :as => 'contact_us'
  get '/welcome/careers', :as => 'careers'
  get '/welcome/about', :as => 'about'

  root "welcome#index"


  resources :hunts do
    resources :tasks do
      resources :completed_tasks, only: [:new, :create]
    end
    resources :comments
  end

  resources :categories
  resources :users
  resources :sessions

end

app/models/hunt.rb
class Hunt < ApplicationRecord
  has_many :participations
  has_many :users, through: :participations
  belongs_to :user #owner
  has_many :comments
  has_many :tasks
  belongs_to :category

  # scope :chronological_order, -> {order(hunt_date: :desc)}
  # scope :past_hunts, -> {where("'#{Date.today}' > hunt_date").order(hunt_date: :desc)}



  validates :name, :difficulty_level, :category, :hunt_time, :hunt_date, :max_participants, presence: true
  # validates :hunt_date, inclusion:{ in: (Date.today-6.months..Date.today+6.months)}
  # validates :hunt_time, inclusion:{ in: (8.hours..20.hours)}
  validates :max_participants, inclusion: { in: (1..20)}

  def self.future_hunts #class method, must be an ActiveRecord Relation fo this to work or be called on the Class.
    self.where('hunt_date > ?', Date.today).order(hunt_date: :asc)
  end

  def self.past_hunts
    self.where('hunt_date < ?', Date.today).order(hunt_date: :desc)
  end



  def difflevel_int_to_text
    case self.difficulty_level
    when 1
      return "Easy"
    when 2
      return "Average"
    when 3
      return "Hard"
    end
  end

  def available_spots
    return self.max_participants - self.users.count
  end

  def hunt_exists_on_that_day?
    answer = []
    my_created_hunts = self.user.hunts
    answer << my_created_hunts.find_by(hunt_date: self.hunt_date)
    answer.nil? ? true : false
  end

end

app/controllers/hunt_controller.rb
class HuntController < ApplicationController

    before_action :select_hunt, except: [:index, :new, :create]

    def index
      # @hunts = Hunt.all
      @categories = Category.all
    end

    def new
      @hunt = Hunt.new
    end

    def create
      @hunt = Hunt.new
    end

    def show
    end

    def edit
    end

    def update
    end

    def delete
    end
end

private

def select_hunt
    @hunt = Hunt.find(params[:id])
end

def categories_hunts
  @categories = Category.all
end

app/controllers/hunts_controller.rb
class HuntsController < ApplicationController

  before_action :select_hunt, except: [:index, :new, :create, :search]
  before_action :set_up_new, only: [:new, :create]
  before_action :categories_hunts, only: [:index, :new, :create, :edit, :update]

  def index
  end

  def new
  end

  def show
    @tasks = @hunt.tasks
    @comment = Comment.new
    @comments = @hunt.comments
  end

  def create
    @hunt.hunt_date = params[:hunt][:hunt_date]
    @hunt.user_id = session[:user_id]
    @category = Category.find_by(id: params[:category_id])
    if @hunt.hunt_exists_on_that_day?
        params[:hunt] = nil
        flash.now[:alert] = "You cannot create more than 1 hunt per day!"
        render :new
    else
      @hunt.name = params[:hunt][:name]
      @hunt.difficulty_level = params[:difficulty_level]
      @hunt.category_id = params[:category_id]
      @hunt.hunt_date = params[:hunt][:hunt_date]
      @hunt.hunt_time = params[:hunt][:hunt_time]
      @hunt.max_participants = params[:hunt][:max_participants]
      @hunt.user_id = session[:user_id]
      if @hunt.save
        # flash[:notice] = "Hunt added!"
        redirect_to new_hunt_task_path(@hunt), info: "Hunt Added !"
      else
        # puts @hunt.errors.full_messages
        params[:hunt] = nil
        render :new
      end
    end
  end

  def edit
    @category = Category.find_by(id: params[:category_id])
  end

  def update
    @hunt.name = params[:hunt][:name]
    @hunt.difficulty_level = params[:difficulty_level]
    @hunt.category_id = params[:category_id]
    @hunt.hunt_date = params[:hunt][:hunt_date]
    @hunt.hunt_time = params[:hunt][:hunt_time]
    @hunt.max_participants = params[:hunt][:max_participants]
    @category = Category.find_by(id: params[:category_id])
    if @hunt.save
      # flash[:notice] = "Hunt updated!"
      redirect_to hunt_path(@hunt), info: "Hunt updated!"
    else
      # puts @hunt.errors.full_messages
      params[:hunt] = nil
      render :edit
    end
  end

  def destroy
    @hunt.destroy
    if @hunt.destroy
      # flash[:notice] = "Hunt deleted!"
      redirect_to hunts_path, info: "Hunt deleted!"
    end
  end

  def search
    if params[:hunt]
      @hunts = Hunt.where("name like ?", "%#{params[:hunt]}%")
      if @hunts.count >= 0
        flash.now[:notice] = "This search returned #{@hunts.count} hunt(s)."
      elsif params[:hunt] == ""
        flash.now[:notice] = "This search returned all hunts!"
      end
    end
  end

  def join
    if @hunt.available_spots == 0
      flash[:notice] = "This Hunt is fully booked"
    else
      if @hunt.users.include?(current_user)
        flash[:alert] = "You cannot join the hunt twice!"
      else
        @hunt.users << current_user
        flash[:notice] = "You have joined the hunt!"

      end
    end
    redirect_to hunt_path
  end

  def unjoin
    if @hunt.users.include?(current_user)
      @hunt.users.delete(current_user)
      flash[:notice] = "You have left the hunt!"
    end
    redirect_to hunt_path
  end

  private

  def set_up_new
    @hunt = Hunt.new
  end

  def select_hunt
    @hunt = Hunt.find(params[:id])
  end

  def categories_hunts
    @categories = Category.all
  end
end

app/helpers/hunt_helper.rb
module HuntHelper



end

app/views/hunts/_form_new_hunt.html.erb
<%= form_for (hunt) do |f| %>


<div class="error_css">
    <%  if @hunt.errors.any? %>
        <h2> Errors ! </h2>

        <ul>
            <%  @hunt.errors.full_messages.each do |message| %>
              <li> <%= message %> </li>
            <% end  %>
        </ul>
    <% end %>
</div>

<h3> <%= f.label :name %> </h3>
  <%= f.text_field :name %>

  <p><fieldset><legend>Difficulty_level</legend>
    <%= radio_button_tag(:difficulty_level, "1") %>
    <%= label_tag(:difficulty_level, "Easy") %>
    <%= radio_button_tag(:difficulty_level, "2") %>
    <%= label_tag(:difficulty_level, "Average") %>
    <%= radio_button_tag(:difficulty_level, "3") %>
    <%= label_tag(:difficulty_level, "Hard") %>
  </p></fieldset>

  <p><fieldset><legend>Category</legend>

    <% categories.each do |category| %>
      <%= radio_button_tag(:category_id, "#{category.id}") %>
      <%= label_tag(:category_id, "#{category.name}") %>
    <% end %>
  </p></fieldset>

<h3>  <%= f.label :hunt_date %></h3>
      <%= f.date_field :hunt_date, min: Date.tomorrow %>

<h3>  <%= f.label :hunt_time %></h3>
      <%= f.time_field :hunt_time, step: 1800%>

<h3>  <%= f.label(:max_participants)%></h3>
      <%= f.number_field :max_participants, value: 20, min: 1, max: 20 %>

<h3> <%= f.submit "ADD"%></h3>
<%end %>

app/views/hunts/create.html.erb
<h1>Hunt#create</h1>
<p>Find me in app/views/hunt/create.html.erb</p>

app/views/hunts/delete.html.erb
<h1>Hunt#delete</h1>
<p>Find me in app/views/hunt/delete.html.erb</p>

app/views/hunts/edit.html.erb
<h1>Edit: <span><%=@hunt.name%><span></h1>
  <div class="links_nav">
    <%=  link_to("Back to Hunt ", hunt_path(@hunt)) %>
  </div>


<%= render 'hunts/form_new_hunt', hunt: @hunt, category: @category, categories: @categories %>

<div class="delete_hunt">
  <%= link_to('Delete Hunt', hunt_path(@hunt), method: :delete, data: {confirm: "Are you sure you want to delete this hunt?"}) %>
</div>

app/views/hunts/edit.it.html.erb
<h1>Modificare: <span><%=@hunt.name%><span></h1>
  <div class="links_nav">
    <%=  link_to("Ritornare alle Cacce ", hunt_path(@hunt)) %>
  </div>


<%= render 'hunts/form_new_hunt', hunt: @hunt, category: @category, categories: @categories %>

<div class="delete_hunt">
  <%= link_to('Cancellare Caccia', hunt_path(@hunt), method: :delete, data: {confirm: "Sei sicuro di voler cancellare questa caccia?"}) %>
</div>

app/views/hunts/index.html.erb
<h1 class="all-hunts">ALL FUTURE HUNTS</h1>

<hr>
<div class="block">

    <% @categories.each do |category|%>
      <div class="categories_hunts">
        <h2><span><%= link_to(category.name, category_path(category))%></span></h2>
      <% category.hunts.each do |hunt|%>
        <div class = "index_hunt">
            <h3><%=link_to("#{hunt.name}", hunt_path(hunt))%></h3>
            <h3>Created by: <span><%=link_to("#{hunt.user.full_name}", user_path(hunt.user))%></span></h3>
            <h3>Date: <span><%=hunt.hunt_date.strftime("%v")%></span></h3>
            <h3>Time: <span><%=hunt.hunt_time.strftime("%H:%M")%></span></h3>
            <h3>Difficulty:
              <span><%hunt.difficulty_level.times do %>
                        <%= image_tag 'raccoon-logo-png.png', :class => "logo_img_diff", :width => "30", :length => "30" %>
                    <%end%>
              </span>
            </h3>
            <h3>Tasks: <span><%=hunt.tasks.count%></h3>
            <h3>Available spots: <span><%=hunt.available_spots%></span></h3>
        </div>
      <%end%>
      </div>
    <%end%>
</div>

app/views/hunts/index.it.html.erb
<h1 class="all-hunts">CACCE A VENIRE</h1>

<hr>
<div class="block">

    <% @categories.each do |category|%>
      <div class="categories_hunts">
        <h2><span><%= link_to(category.name, category_path(category))%></span></h2>
      <% category.hunts.each do |hunt|%>
        <div class = "index_hunt">
            <h3><%=link_to("#{hunt.name}", hunt_path(hunt))%></h3>
            <h3>Creata da: <span><%=link_to("#{hunt.user.full_name}", user_path(hunt))%></span></h3>
            <h3>Data: <span><%=hunt.hunt_date.strftime("%v")%></span></h3>
            <h3>Orario: <span><%=hunt.hunt_time.strftime("%H:%M")%></span></h3>
            <h3>Difficolta:
              <span><%hunt.difficulty_level.times do %>
                        <%= image_tag 'raccoon-logo-png.png', :class => "logo_img_diff", :width => "30", :length => "30" %>
                    <%end%>
              </span>
            </h3>
            <h3>Prove: <span><%=hunt.tasks.count%></h3>
            <h3>Posti disponibili: <span><%=hunt.available_spots%></span></h3>
        </div>
      <%end%>
      </div>
    <%end%>
</div>

app/views/hunts/new.html.erb
<h3><span class = "hunts_link_back">&#8678; <%= link_to('Back to Hunts', hunts_path) %></span></h3>


<h2 class = "create_hunt">Create your hunt:</h2>

<%= render 'hunts/form_new_hunt', hunt: @hunt, categories: @categories %>

app/views/hunts/new.it.html.erb
<h3><span class = "hunts_link_back">&#8678; <%= link_to('Ritornare alle Cacce', hunts_path) %></span></h3>


<h2 class = "create_hunt">Crea Caccia:</h2>

<%= render 'hunts/form_new_hunt', hunt: @hunt, categories: @categories %>

app/views/hunts/search.html.erb
<h3><span class = "hunts_link_back">&#8678; <%= link_to('Back to Hunts', hunts_path) %></span></h3>

<h1 class="text-center">Search results:</h1>
<hr>


<div class = "block">
  <% @hunts.each do |hunt|%>
    <div class = "index_hunt">
      <h3>Category: <span><%= link_to(hunt.category.name, category_path(hunt.category)) %></span></h3>
      <h3>Hunt name: <span class = "hunt_name"><%= link_to(hunt.name, hunt_path(hunt)) %></span></h3>
      <h3>Created by: <span><%= link_to(hunt.user.full_name, user_path(hunt.user)) %></span></h3>
      <h3>Date of hunt: <span><%=hunt.hunt_date.strftime("%v")%></span></h3>
      <h3>Time of hunt: <span><%=hunt.hunt_time.strftime("%H:%M")%></span></h3>
      <h3>Difficulty:
        <span><%hunt.difficulty_level.times do %>
                  <%= image_tag 'raccoon-logo-png.png', :class => "logo_img_diff", :width => "30", :length => "30" %>
              <%end%>
        </span>
      </h3>
      <h3>Tasks: <span><%=hunt.tasks.count%></h3>
      <h3>Available spots: <span><%=hunt.available_spots%></span></h3>
    </div>
  <%end%>
</div>

app/views/hunts/search.it.html.erb
<h3><span class = "hunts_link_back">&#8678; <%= link_to('Ritornare alla Cacce', hunts_path) %></span></h3>

<h1 class="text-center">Risulato ricerca:</h1>
<hr>


<div class = "block">
  <% @hunts.each do |hunt|%>
    <div class = "index_hunt">
      <h3>Categoria: <span><%= link_to(hunt.category.name, category_path(hunt.category)) %></span></h3>
      <h3>Titolo caccia: <span class = "hunt_name"><%= link_to(hunt.name, hunt_path(hunt)) %></span></h3>
      <h3>Creata da: <span><%= link_to(hunt.user.full_name, user_path(hunt.user)) %></span></h3>
      <h3>Data caccia: <span><%=hunt.hunt_date.strftime("%v")%></span></h3>
      <h3>Orario caccia: <span><%=hunt.hunt_time.strftime("%H:%M")%></span></h3>
      <h3>Difficolta:
        <span><%hunt.difficulty_level.times do %>
                  <%= image_tag 'raccoon-logo-png.png', :class => "logo_img_diff", :width => "30", :length => "30" %>
              <%end%>
        </span>
      </h3>
      <h3>Prove: <span><%=hunt.tasks.count%></h3>
      <h3>Posti disponibili: <span><%=hunt.available_spots%></span></h3>
    </div>
  <%end%>
</div>

app/views/hunts/show.html.erb
<h3><span class = "hunts_link_back">&#8678; <%= link_to('Back to Hunts', hunts_path) %></span></h3>


<h1 class = "hunt_name"><%= @hunt.name %></h1>

<div class = "hunt">
<% if current_user && @hunt.users.include?(current_user) == false %>
    <div class="join_hunt">
      <%= link_to('Join Hunt', hunt_join_path, method: :post, data: {confirm: "Are you sure you want to join this hunt?"}) %>
    </div>
<% end %>

<% if current_user == @hunt.user %>
<div class="edit_hunt_button">
  <%= link_to('Edit Hunt', edit_hunt_path) %>
</div>
<% end %>

<div class = "index_hunt_show">
  <h3>Category: <span><%= link_to("#{@hunt.category.name}", category_path(@hunt.category)) %></span></h3>
  <h3>Created by: <span><%= link_to "#{@hunt.user.full_name}", user_path(@hunt.user) %></span></h3>
  <h3>Date of hunt: <span><%=@hunt.hunt_date.strftime("%v")%></span></h3>
  <h3>Time of hunt: <span><%=@hunt.hunt_time.strftime("%H:%M")%></span></h3>
  <h3>Difficulty:
    <span><%@hunt.difficulty_level.times do %>
              <%= image_tag 'raccoon-logo-png.png', :class => "logo_img_diff", :width => "30", :length => "30" %>
          <%end%>
    </span>
  </h3>
  <h3>Tasks: <span><%=@hunt.tasks.count%></h3>
  <h3>Available spots: <span><%=@hunt.available_spots%></span></h3>
</div>

  <h3>Participants to the hunt:</h3>
  <% @hunt.users.each do |participant| %>
    <div class="hunt_participants">
      <li><%= link_to "#{participant.full_name}", user_path(participant) %>
        <%if current_user %>
          <%if participant.id == current_user.id %>
            | <span><%= link_to('Leave this hunt', hunt_unjoin_path, method: :post, data: {confirm: "Are you sure you want to leave this hunt?"})%></span>
          <% end %>
        <% else %>
          <% flash.now[:warning] = "Please log in if you want to join it!"%>
        <% end %></li>
    </div>
  <% end %>
</div>


<h2>Tasks :</h2>
  <% if current_user == @hunt.user %>
      <div class="add_new_task">
        <%= link_to 'Add New Task', new_hunt_task_path(@hunt) %></h2>
      </div>
  <% end %>

<% if @hunt.users.include?(current_user) %>
<h3>Progress: </h3>
  <div id="progressbar">
    <div id="mybar"></div>
  </div>
<br>
<% end %>
  <div class="tasks">
     <% @tasks.each do |t| %>
        <div class = "task"  >
          <% if current_user && t.completed_by_user?(current_user) == true %>
          <p class = "completed_task">Task completed !</p>
          <% end %>
          <p> Details: <%= link_to "#{t.details}", "/hunts/#{@hunt.id}/tasks/#{t.id}" %></p>
          <p> Address: <span class = "taskaddress"> <%= t.address  %></span></p>
          <p> Neighbourhood: <%= t.neighbourhood %> </p>
          <% if current_user == @hunt.user %>
          <div class="edit_task">
            <li><%= link_to 'Edit Task', "/hunts/#{@hunt.id}/tasks/#{t.id}/edit" %> </li> |
            <li><%= link_to 'Delete Task', "/hunts/#{@hunt.id}/tasks/#{t.id}", method: :delete %></li>
          </div>
          <% end %>
        </div>
     <% end  %>
  </div>



<div id = "mapid_all">
</div>


<%= render(partial: 'comments/form', locals: { hunt: @hunt, comment: @comment }) %>

<% @comments.each do |comment| %>
  <p>posted by:  <%= comment.user.first_name %>   on   <%= comment.created_at.strftime("%B %d, %Y") %> <%= comment.created_at.strftime("%I:%M %p ") %></p>
  <p><%= comment.description %></p>
<% end %>

app/views/hunts/show.it.html.erb
<h3><span class = "hunts_link_back">&#8678; <%= link_to('Ritornare alle Cacce', hunts_path) %></span></h3>


<h1 class = "hunt_name"><%= @hunt.name %></h1>

<div class = "hunt">
<% if current_user && @hunt.users.include?(current_user) == false %>
    <div class="join_hunt">
      <%= link_to('Unirsi alla Caccia', hunt_join_path, method: :post, data: {confirm: "Sei sicuro di voler unirsi a questa caccia?"}) %>
    </div>
<% end %>

<% if current_user == @hunt.user %>
<div class="edit_hunt_button">
  <%= link_to('Modifica Caccia', edit_hunt_path) %>
</div>
<% end %>

<div class = "index_hunt_show">
  <h3>Categoria: <span><%= link_to("#{@hunt.category.name}", category_path(@hunt.category)) %></span></h3>
  <h3>Creata da: <span><%= link_to "#{@hunt.user.full_name}", user_path(@hunt.user) %></span></h3>
  <h3>Data caccia: <span><%=@hunt.hunt_date.strftime("%v")%></span></h3>
  <h3>Orario caccia: <span><%=@hunt.hunt_time.strftime("%H:%M")%></span></h3>
  <h3>Difficolta':
    <span><%@hunt.difficulty_level.times do %>
              <%= image_tag 'raccoon-logo-png.png', :class => "logo_img_diff", :width => "30", :length => "30" %>
          <%end%>
    </span>
  </h3>
  <h3>Prove: <span><%=@hunt.tasks.count%></h3>
  <h3>Posti disponibili: <span><%=@hunt.available_spots%></span></h3>
</div>

  <h3>Membri della caccia:</h3>
  <% @hunt.users.each do |participant| %>
    <div class="hunt_participants">
      <li><%= link_to "#{participant.full_name}", user_path(participant) %>
        <%if current_user %>
          <%if participant.id == current_user.id %>
            | <span><%= link_to('Lasciare la caccia', hunt_unjoin_path, method: :post, data: {confirm: "Sei sicuro di voler lasciare questa caccia?"})%></span>
          <% end %>
        <% else %>
          <% flash.now[:warning] = "Prima di unirsi alla caccia e' necessario completare il login!"%>
        <% end %></li>
    </div>
  <% end %>
</div>



<h2>Prove :</h2>
  <% if current_user == @hunt.user %>
      <div class="add_new_task">
        <%= link_to 'Aggiungere Prova', new_hunt_task_path(@hunt) %></h2>
      </div>
  <% end %>
  <div class="tasks">
     <% @tasks.each do |t| %>
        <div class = "task"  >
          <p> Dettagli: <%= link_to "#{t.details}", "/hunts/#{@hunt.id}/tasks/#{t.id}" %></p>
          <p> Indirizzo: <span class = "taskaddress"> <%= t.address  %></span></p>
          <p> Quartiere: <%= t.neighbourhood %> </p>
          <% if current_user == @hunt.user %>
          <div class="edit_task">
            <li><%= link_to 'Modifica Prova', "/hunts/#{@hunt.id}/tasks/#{t.id}/edit" %> </li> |
            <li><%= link_to 'Cancellare Prova', "/hunts/#{@hunt.id}/tasks/#{t.id}", method: :delete %></li>
          </div>
          <% end %>
        </div>
     <% end  %>
  </div>



<div id = "mapid_all">
</div>


<%= render(partial: 'comments/form', locals: { hunt: @hunt, comment: @comment }) %>

<% @comments.each do |comment| %>
  <p>lasciato da:  <%= comment.user.first_name %>   a   <%= comment.created_at.strftime("%B %d, %Y") %> <%= comment.created_at.strftime("%I:%M %p ") %></p>
  <p><%= comment.description %></p>
<% end %>