config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  post '/hunts/:id/join' => "hunts#join", :as => 'hunt_join'
  post '/hunts/:id/unjoin' => "hunts#unjoin", :as => 'hunt_unjoin'
  post '/hunts/search', :as => 'hunt_search'
  patch '/users/:id/update_public' => "users#update_public", :as => 'users_profile'
  get '/welcome/team', :as => 'contact_us'
  get '/welcome/careers', :as => 'careers'
  get '/welcome/about', :as => 'about'

  root "welcome#index"


  resources :hunts do
    resources :tasks do
      resources :completed_tasks, only: [:new, :create]
    end
    resources :comments
  end

  resources :categories
  resources :users
  resources :sessions

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :hunts
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def show
    @category = Category.find(params[:id])
  end


  def update
  end

  def delete
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController

  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/categories/create.html.erb
<h1>Category#create</h1>
<p>Find me in app/views/category/create.html.erb</p>

app/views/categories/delete.html.erb
<h1>Category#delete</h1>
<p>Find me in app/views/category/delete.html.erb</p>

app/views/categories/edit.html.erb
<h1>Category#edit</h1>
<p>Find me in app/views/category/edit.html.erb</p>

app/views/categories/index.html.erb
<h1>Category#index</h1>
<p>Find me in app/views/category/index.html.erb</p>

app/views/categories/new.html.erb
<h1>Category#new</h1>
<p>Find me in app/views/category/new.html.erb</p>

app/views/categories/show.html.erb
<h3><span class = "hunts_link_back">&#8678; <%= link_to('Back to Hunts', hunts_path) %></span></h3>

<div class = "category_header">
  <h1><%= @category.name %> Hunts</h1>
</div>
<hr>
<div class="block">
      <% @category.hunts.each do |hunt|%>
        <div class="index_hunt">
              <h3><%=link_to(hunt.name, hunt_path(hunt)) %></h3>
              <h3>Created by: <span><%=link_to(hunt.user.full_name, user_path(hunt.user)) %></span></h3>
              <h3>Date of hunt: <span><%=hunt.hunt_date.strftime("%v")%></span></h3>
              <h3>Time of hunt: <span><%=hunt.hunt_time.strftime("%H:%M")%></span></h3>
              <h3>Difficulty:
                <span><%hunt.difficulty_level.times do %>
                          <%= image_tag 'raccoon-logo-png.png', :class => "logo_img_diff", :width => "30", :length => "30" %>
                      <%end%>
                </span>
              </h3>
              <h3>Tasks: <span><%=hunt.tasks.count%></h3>
              <h3>Available spots: <span><%=hunt.available_spots%></span></h3>
        </div>
        <%end%>
</div>

app/views/categories/update.html.erb
<h1>Category#update</h1>
<p>Find me in app/views/category/update.html.erb</p>