config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  post '/hunts/:id/join' => "hunts#join", :as => 'hunt_join'
  post '/hunts/:id/unjoin' => "hunts#unjoin", :as => 'hunt_unjoin'
  post '/hunts/search', :as => 'hunt_search'
  patch '/users/:id/update_public' => "users#update_public", :as => 'users_profile'
  get '/welcome/team', :as => 'contact_us'
  get '/welcome/careers', :as => 'careers'
  get '/welcome/about', :as => 'about'

  root "welcome#index"


  resources :hunts do
    resources :tasks do
      resources :completed_tasks, only: [:new, :create]
    end
    resources :comments
  end

  resources :categories
  resources :users
  resources :sessions

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :hunts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :hunt

  validates :description, presence: true
end

app/models/completed_task.rb
class CompletedTask < ApplicationRecord
  belongs_to :user
  belongs_to :task

  has_one_attached :image

  validates :proof, :completed, presence: true
end

app/models/hunt.rb
class Hunt < ApplicationRecord
  has_many :participations
  has_many :users, through: :participations
  belongs_to :user #owner
  has_many :comments
  has_many :tasks
  belongs_to :category

  # scope :chronological_order, -> {order(hunt_date: :desc)}
  # scope :past_hunts, -> {where("'#{Date.today}' > hunt_date").order(hunt_date: :desc)}



  validates :name, :difficulty_level, :category, :hunt_time, :hunt_date, :max_participants, presence: true
  # validates :hunt_date, inclusion:{ in: (Date.today-6.months..Date.today+6.months)}
  # validates :hunt_time, inclusion:{ in: (8.hours..20.hours)}
  validates :max_participants, inclusion: { in: (1..20)}

  def self.future_hunts #class method, must be an ActiveRecord Relation fo this to work or be called on the Class.
    self.where('hunt_date > ?', Date.today).order(hunt_date: :asc)
  end

  def self.past_hunts
    self.where('hunt_date < ?', Date.today).order(hunt_date: :desc)
  end



  def difflevel_int_to_text
    case self.difficulty_level
    when 1
      return "Easy"
    when 2
      return "Average"
    when 3
      return "Hard"
    end
  end

  def available_spots
    return self.max_participants - self.users.count
  end

  def hunt_exists_on_that_day?
    answer = []
    my_created_hunts = self.user.hunts
    answer << my_created_hunts.find_by(hunt_date: self.hunt_date)
    answer.nil? ? true : false
  end

end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :user
  belongs_to :hunt

end

app/models/task.rb
class Task < ApplicationRecord
  has_many :completed_tasks
  has_many :users, through: :completed_tasks
  belongs_to :hunt

  validates :details, presence: true
  # validates :address, presence: true
  # validates :neighbourhood, presence: true

  def completed_by_user?(user)
    @tasks_completed = CompletedTask.all
    @tasks_completed.each do |completed|
      if (user.id == completed.user_id && self.id == completed.task_id)
        return true
      end
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :participations, dependent: :destroy
  has_many :participated_hunts, through: :participations, source: :hunt
  has_many :completed_tasks, dependent: :destroy
  has_many :tasks, through: :completed_tasks
  has_many :hunts #owned_hunt
  has_many :comments, dependent: :destroy

  validates :first_name, :last_name, presence: true
  validates :password, confirmation: true, on: :create
  validates :password_confirmation, presence: true, on: :create
  validates :email, presence: true, on: :create
  validates :email, uniqueness: true

  def full_name
    return "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/hunt_controller.rb
class HuntController < ApplicationController

    before_action :select_hunt, except: [:index, :new, :create]

    def index
      # @hunts = Hunt.all
      @categories = Category.all
    end

    def new
      @hunt = Hunt.new
    end

    def create
      @hunt = Hunt.new
    end

    def show
    end

    def edit
    end

    def update
    end

    def delete
    end
end

private

def select_hunt
    @hunt = Hunt.find(params[:id])
end

def categories_hunts
  @categories = Category.all
end

app/controllers/hunts_controller.rb
class HuntsController < ApplicationController

  before_action :select_hunt, except: [:index, :new, :create, :search]
  before_action :set_up_new, only: [:new, :create]
  before_action :categories_hunts, only: [:index, :new, :create, :edit, :update]

  def index
  end

  def new
  end

  def show
    @tasks = @hunt.tasks
    @comment = Comment.new
    @comments = @hunt.comments
  end

  def create
    @hunt.hunt_date = params[:hunt][:hunt_date]
    @hunt.user_id = session[:user_id]
    @category = Category.find_by(id: params[:category_id])
    if @hunt.hunt_exists_on_that_day?
        params[:hunt] = nil
        flash.now[:alert] = "You cannot create more than 1 hunt per day!"
        render :new
    else
      @hunt.name = params[:hunt][:name]
      @hunt.difficulty_level = params[:difficulty_level]
      @hunt.category_id = params[:category_id]
      @hunt.hunt_date = params[:hunt][:hunt_date]
      @hunt.hunt_time = params[:hunt][:hunt_time]
      @hunt.max_participants = params[:hunt][:max_participants]
      @hunt.user_id = session[:user_id]
      if @hunt.save
        # flash[:notice] = "Hunt added!"
        redirect_to new_hunt_task_path(@hunt), info: "Hunt Added !"
      else
        # puts @hunt.errors.full_messages
        params[:hunt] = nil
        render :new
      end
    end
  end

  def edit
    @category = Category.find_by(id: params[:category_id])
  end

  def update
    @hunt.name = params[:hunt][:name]
    @hunt.difficulty_level = params[:difficulty_level]
    @hunt.category_id = params[:category_id]
    @hunt.hunt_date = params[:hunt][:hunt_date]
    @hunt.hunt_time = params[:hunt][:hunt_time]
    @hunt.max_participants = params[:hunt][:max_participants]
    @category = Category.find_by(id: params[:category_id])
    if @hunt.save
      # flash[:notice] = "Hunt updated!"
      redirect_to hunt_path(@hunt), info: "Hunt updated!"
    else
      # puts @hunt.errors.full_messages
      params[:hunt] = nil
      render :edit
    end
  end

  def destroy
    @hunt.destroy
    if @hunt.destroy
      # flash[:notice] = "Hunt deleted!"
      redirect_to hunts_path, info: "Hunt deleted!"
    end
  end

  def search
    if params[:hunt]
      @hunts = Hunt.where("name like ?", "%#{params[:hunt]}%")
      if @hunts.count >= 0
        flash.now[:notice] = "This search returned #{@hunts.count} hunt(s)."
      elsif params[:hunt] == ""
        flash.now[:notice] = "This search returned all hunts!"
      end
    end
  end

  def join
    if @hunt.available_spots == 0
      flash[:notice] = "This Hunt is fully booked"
    else
      if @hunt.users.include?(current_user)
        flash[:alert] = "You cannot join the hunt twice!"
      else
        @hunt.users << current_user
        flash[:notice] = "You have joined the hunt!"

      end
    end
    redirect_to hunt_path
  end

  def unjoin
    if @hunt.users.include?(current_user)
      @hunt.users.delete(current_user)
      flash[:notice] = "You have left the hunt!"
    end
    redirect_to hunt_path
  end

  private

  def set_up_new
    @hunt = Hunt.new
  end

  def select_hunt
    @hunt = Hunt.find(params[:id])
  end

  def categories_hunts
    @categories = Category.all
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/hunt_helper.rb
module HuntHelper



end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper







end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrbanHunter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.4/dist/leaflet.css"
       integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA=="
       crossorigin=""/>

    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>

    <script src="https://unpkg.com/leaflet@1.3.4/dist/leaflet.js"
        integrity="sha512-nMMmRyTVoLYqjP9hrbed9S+FzjZHW5gY1TWCHA5ckwXZBadntCNs8kEqAWdrb9O7rxbCaA4lKTIWjDXZxflOcA=="
        crossorigin="">
    </script>

    <meta name="google" content="notranslate">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    <% %w(192 512).each do |s| %>
      <%= favicon_link_tag "android-chrome-#{s}x#{s}.png", rel: 'android-chrome-icon', type: 'image/png', sizes: "#{s}x#{s}" %>
    <% end %>

      <%= favicon_link_tag "apple-touch-icon.png", rel: 'apple-touch-icon', type: 'image/png' %>

    <% %w(16 32).each do |s| %>
      <%= favicon_link_tag "favicon-#{s}x#{s}.png", rel: 'icon', type: 'image/png', sizes: "#{s}x#{s}" %>
    <% end %>
  </head>

  <body>

    <div class="lang_switch">
    <%if !request.path_info.include?("search") %>
        <span id="switch_lang"><%=link_to("🇨🇦", {:locale=>"en"}, :id => "en")%>  <%=link_to("🇮🇹", {:locale=>"it"}, :id => "it")%>   <%=link_to("🇫🇷", {:locale=>"fr"}, :id => "fr")%>  <%=link_to("🇯🇵", {:locale=>"jp"}, :id => "jp")%>  <%=link_to("🇩🇪", {:locale=>"de"}, :id => "de")%>
        </span>
    <%end%>

    </div>

    <div class="navigation_bar">
      <div class="side_nav_button">
        <span id="open_button" class="open_button" onclick="openNav()"><%=t("welcome_controller.index.menu")%></span>
      </div>
      <div class="nav_1">
        <div class="logo">
          <div class="top_left">
            <%= image_tag 'raccoon-logo-png.png', :class => "logo_img", :width => "100", :length =>"100" %>
          </div>
          <div class="top_center">
            <%= link_to "Urban Hunter", root_path, :class => "logo_text" %>
          </div>
        </div>
          <div class="top_right">
            <ul class="user_options">
              <% if current_user%>
                <div class="logged_in">
                  <% if !request.path_info.include?("search") %>
                    <li><%= link_to t("welcome_controller.index.hello") + " " + "#{current_user.first_name}", user_path(current_user) %></li>
                    <li><%= link_to t("welcome_controller.index.sign_out"), session_path("purple"), :method => :delete %></li>
                  <% end %>
                </div>
              <% else %>
                <div class="logged_out">
                  <% if !request.path_info.include?("search") %>
                    <li class="sign_in"><%= link_to t("welcome_controller.index.sign_up"), new_user_path %></li>
                    <li class="log_in"><%= link_to t("welcome_controller.index.log_in"), new_session_path, :class => "login_button" %></li>
                  <% end %>
                </div>
              <% end %>
            </ul>
          </div>
      </div>
      <div class="nav_2">
        <div class="">
          <div class="user_options">
            <% if current_user %>
            <%= link_to(t("welcome_controller.index.make_hunt"), new_hunt_path) %>
            <% end %>
          </div>
          <div class="search_bar">
            <%= form_tag(hunt_search_path, {:id => 'search_form'}) do %>
            <%= text_field_tag :hunt, params[:hunt], :class => "search_field" %><%= submit_tag t("welcome_controller.index.search_button"), :placeholder => 'Search for hunts!', name: nil, :class => "search_button" %>
          </div>
          <% end %>
        </div>

      </div>


        <br>
      </div>
    </div>


      <div id="mySidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <div class = "next_5_hunts">
          <h2><%=t("welcome_controller.index.next_5_hunts")%></h2>
        </div>
        <% if @future_hunts_five.count > 0 %>
        <div class = "firsthunt">
          <p>
            <%d = @future_hunts_five[0].hunt_date%>
            <%t = Time.parse(@future_hunts_five[0].hunt_time.to_s)%>
            <%time = Time.now%>
            <%first_future_hunt_time = DateTime.new(d.year, d.month, d.day, t.hour, t.min, t.sec, time.zone)%>
            <input type = "hidden" value = "<%=first_future_hunt_time%>" id = "deadline"/>
            <%=link_to("#{@future_hunts_five[0].name}", hunt_path(@future_hunts_five[0])) %></p>
            <p><%=t("welcome_controller.index.hunt_starts")%></p>
        </div>


        <div id="clockdiv">
          <div>
            <span class="days"></span>
            <div class="smalltext">Days</div>
          </div>
          <div>
            <span class="hours"></span>
            <div class="smalltext">Hrs</div>
          </div>
          <div>
            <span class="minutes"></span>
            <div class="smalltext">Min</div>
          </div>
          <div>
            <span class="seconds"></span>
            <div class="smalltext">Sec</div>
          </div>
        </div>

        <div class = "first_4">
            <% @future_hunts_five[1..4].each do |hunt| %>
               <p><%=link_to("#{hunt.name}", hunt_path(hunt))%></p>
            <% end %>
        </div>

        <%else%>
          <p><%=t("welcome_controller.index.no_hunts")%></p>
        <%end%>

        <div class = "nav_hrz_divider">
          <%= image_tag 'raccoon-logo-png.png', :class => "logo_img_mini", :width => "50", :length => "50" %>
          <%= image_tag 'raccoon-logo-png.png', :class => "logo_img_mini", :width => "50", :length => "50" %>
          <%= image_tag 'raccoon-logo-png.png', :class => "logo_img_mini", :width => "50", :length => "50" %>
          <%= image_tag 'raccoon-logo-png.png', :class => "logo_img_mini", :width => "50", :length => "50" %>
        </div>

        <div class="all_hunts_homepage">
          <%= link_to(t("welcome_controller.index.all_hunts"), hunts_path) %>
        </div>

        <div class = "nav_hrz_divider">
          <%= image_tag 'raccoon-logo-png.png', :class => "logo_img_mini", :width => "50", :length => "50" %>
          <%= image_tag 'raccoon-logo-png.png', :class => "logo_img_mini", :width => "50", :length => "50" %>
          <%= image_tag 'raccoon-logo-png.png', :class => "logo_img_mini", :width => "50", :length => "50" %>
          <%= image_tag 'raccoon-logo-png.png', :class => "logo_img_mini", :width => "50", :length => "50" %>
        </div>

      <div class = "project-info">
        <p><%= link_to(t("welcome_controller.index.about_us"), about_path) %></p>
        <p><%= link_to(t("welcome_controller.index.contact_us"), contact_us_path) %></p>
        <p><%= link_to(t("welcome_controller.index.careers"), careers_path) %></p>
      </div>

    </div>

    <main>
      <% flash.each do |key, message| %>
      <div class="flash-<%= key %>"><span class="error_message"><%= message %><span></div>
      <% end %>
       <%= render 'sessions/form' %>
       <%= render 'users/form' %>
      <%= yield %>
    </main>
    <footer>
      <div class="info_nav">
        <ul class="info_list">
          <p><%=t("welcome_controller.index.made_by")%></p>
          <li><%= link_to(t("welcome_controller.index.contact_us"), contact_us_path) %></li>
          <li><%= link_to(t("welcome_controller.index.about_us"), about_path) %></li>
          <p><%=t("welcome_controller.index.happy_hunting")%></p>
        </ul>
      </div>
    </footer>
  </body>
</html>